### ISSUE TITLE
Provide a true eager config loading system

### ISSUE THREAD

**Issue by Olical** [Olical/magic-kit#2]
The existing config systems that packer exposes seem to always load things too late / async which means you can't set things before the plugins are loaded. We need a simple and obvious way to load plugin config as early as possible.

**Comment by leiserfg** [comment]
The only solution I can think of is to ask the packer guys to add a way for making a plugin load before the rest or to call a function before any plugin, and then load the options there, but I don't think they will like it as that's very niche because that's just the same as putting that function in the `init.lua`.

**Comment by Olical** [comment]
I've integrated my `:mod` syntax (short for module) that eagerly loads a module as you specify your plugins. If you do this you'll have to use vim.schedule or something inside the config module to defer any code that has to be run _after_ the plugins have loaded. Or use `:config` and `:mod` for different things, some for eager, some for lazy.
